name: Test Secrets

on:
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test Secrets
        run: |
          echo "DATABASE_URL: ${{ secrets.DATABASE_URL }}"
          echo "DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}"
          echo "DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}"
          echo "EMAIL_HOST: ${{ secrets.EMAIL_HOST }}"
          echo "EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}"
          echo "EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}"
          echo "EMAIL_PORT: ${{ secrets.EMAIL_PORT }}"
          echo "GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}"
          echo "GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}"
          echo "GOOGLE_SCOPE: ${{ secrets.GOOGLE_SCOPE }}"
